/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sikopet;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class DataWarga extends javax.swing.JFrame {
    
    DefaultTableModel model;
    
   public DataWarga() {
        initComponents();
        //untuk tabel
        String[] judul = {"ID","Nama","NIK","No HP","Jumlah","Kategori","Tanggal"};
        model = new DefaultTableModel(judul,0);
        tblDatawarga.setModel(model);
        getData();
          // POSISI TENGAH LAYAR:
        setLocationRelativeTo(null); // ini penting
        
        //combobox
        cmbJumlah.setModel(new javax.swing.DefaultComboBoxModel<> (new String[] {
            "RP. 100.000", "RP 200.000", "RP. 300.000", "RP. 400.000", "RP. 500.000",
            "RP. 600.000", "RP. 700.000", "RP.800.000", "RP.900.000", "RP.1.000.000" }));
        
        cmbTgl.setModel(new javax.swing.DefaultComboBoxModel<> (new String[] {
            "1", "2", "3", "4","5","6","7", "8", "9", "10","11","12","13", 
            "14", "15", "16","17","18","19", "20", "21", "22","23","24",
             "25", "26", "27","28","29","30", "31"}));
        
         cmbBln.setModel(new javax.swing.DefaultComboBoxModel<> (new String[] {
            "JAN", "FEB", "MAR", "APR","MEI","JUN","JUL", 
             "AGU", "SEP", "OKT","NOV","DES" }));
          cmbThn.setModel(new javax.swing.DefaultComboBoxModel<> (new String[] {
            "2025", "2026", "2027" }));
      
        //rb
        bg_Kategori.add(rb_Pemasukan);
        bg_Kategori.add(rb_Pengeluaran);
        
        //mouse
        tblDatawarga.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                int row = tblDatawarga.getSelectedRow();
                
                txtNama.setText(tblDatawarga.getValueAt(row,1).toString());
                txtNik.setText(tblDatawarga.getValueAt(row,2).toString());
                txtNohp.setText(tblDatawarga.getValueAt(row,3).toString());
                cmbJumlah.setSelectedItem(tblDatawarga.getValueAt(row,4).toString());
                
                String Kategori  = tblDatawarga.getValueAt(row, 5).toString();
                
                // Parse tanggal dari tabel
                String tanggalStr = tblDatawarga.getValueAt(row, 6).toString();
                if (tanggalStr != null && !tanggalStr.isEmpty()) {
                    String[] tanggalParts = tanggalStr.split("/");
                    if (tanggalParts.length == 3) {
                        cmbTgl.setSelectedItem(tanggalParts[0]);
                        cmbBln.setSelectedItem(tanggalParts[1]);
                        cmbThn.setSelectedItem(tanggalParts[2]);
                    }
                }
                switch(Kategori){
                    case "Pemasukan":
                        rb_Pemasukan.setSelected(true);
                        break;
                    case "Pengeluaran":
                        rb_Pengeluaran.setSelected(true);
                        break;
                    
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg_Kategori = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        nik = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtKategori = new javax.swing.JLabel();
        rb_Pemasukan = new javax.swing.JRadioButton();
        rb_Pengeluaran = new javax.swing.JRadioButton();
        Jumlah = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatawarga = new javax.swing.JTable();
        btnTambahkan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        cmbJumlah = new javax.swing.JComboBox<>();
        Nohp = new javax.swing.JLabel();
        txtNohp = new javax.swing.JTextField();
        tgl = new javax.swing.JLabel();
        cmbTgl = new javax.swing.JComboBox<>();
        cmbBln = new javax.swing.JComboBox<>();
        cmbThn = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuopen = new javax.swing.JMenuItem();
        menusave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        txtDatawarga = new javax.swing.JMenuItem();
        txtKeuangan = new javax.swing.JMenuItem();
        txtLaporan = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data : Data Warga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 102))); // NOI18N

        nama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 0, 102));
        nama.setText("NAMA WARGA");

        nik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nik.setForeground(new java.awt.Color(0, 0, 102));
        nik.setText("NIK");
        nik.setToolTipText("");

        txtNama.setBackground(new java.awt.Color(153, 153, 255));
        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));

        txtNik.setBackground(new java.awt.Color(153, 153, 255));
        txtNik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNik.setForeground(new java.awt.Color(255, 255, 255));

        txtKategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtKategori.setForeground(new java.awt.Color(0, 0, 102));
        txtKategori.setText("KATEGORI");

        rb_Pemasukan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Pemasukan.setForeground(new java.awt.Color(0, 0, 102));
        rb_Pemasukan.setText("PEMASUKAN");

        rb_Pengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rb_Pengeluaran.setForeground(new java.awt.Color(0, 0, 102));
        rb_Pengeluaran.setText("PENGELUARAN");

        Jumlah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jumlah.setForeground(new java.awt.Color(0, 0, 102));
        Jumlah.setText("JUMLAH");

        tblDatawarga.setBackground(new java.awt.Color(153, 153, 255));
        tblDatawarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblDatawarga.setForeground(new java.awt.Color(255, 255, 255));
        tblDatawarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDatawarga);

        btnTambahkan.setBackground(new java.awt.Color(153, 153, 255));
        btnTambahkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambahkan.setForeground(new java.awt.Color(0, 0, 102));
        btnTambahkan.setText("TAMBAHKAN DATA");
        btnTambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahkanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(153, 153, 255));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 102));
        btnEdit.setText("EDIT DATA");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(153, 153, 255));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 0, 102));
        btnHapus.setText("HAPUS DATA");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        cmbJumlah.setBackground(new java.awt.Color(153, 153, 255));
        cmbJumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Nohp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nohp.setForeground(new java.awt.Color(0, 0, 102));
        Nohp.setText("NO HP");
        Nohp.setPreferredSize(new java.awt.Dimension(59, 16));

        txtNohp.setBackground(new java.awt.Color(153, 153, 255));

        tgl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tgl.setForeground(new java.awt.Color(0, 0, 102));
        tgl.setText("TGL/BLN/THN :");

        cmbTgl.setBackground(new java.awt.Color(153, 153, 255));
        cmbTgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbBln.setBackground(new java.awt.Color(153, 153, 255));
        cmbBln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbThn.setBackground(new java.awt.Color(153, 153, 255));
        cmbThn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTambahkan)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama)
                                    .addComponent(nik)
                                    .addComponent(Nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNik, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(txtNama)
                                    .addComponent(txtNohp))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtKategori)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Pengeluaran)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(rb_Pemasukan)
                                                .addGap(38, 38, 38)
                                                .addComponent(Jumlah))
                                            .addComponent(btnHapus))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(cmbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(cmbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKategori)
                    .addComponent(rb_Pemasukan)
                    .addComponent(Jumlah)
                    .addComponent(cmbJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nik)
                    .addComponent(rb_Pengeluaran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl)
                    .addComponent(cmbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahkan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        menuopen.setText("Open");
        jMenu1.add(menuopen);

        menusave.setText("Save");
        menusave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusaveActionPerformed(evt);
            }
        });
        jMenu1.add(menusave);
        jMenu1.add(jSeparator1);

        menuexit.setText("Exit");
        menuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitActionPerformed(evt);
            }
        });
        jMenu1.add(menuexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Input Data");

        txtDatawarga.setText("Data Warga");
        txtDatawarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatawargaActionPerformed(evt);
            }
        });
        jMenu2.add(txtDatawarga);

        txtKeuangan.setText("Pencatatan Keuangan");
        txtKeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeuanganActionPerformed(evt);
            }
        });
        jMenu2.add(txtKeuangan);

        txtLaporan.setText("Laporan");
        jMenu2.add(txtLaporan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatawargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatawargaActionPerformed
     DataWarga newWin = new DataWarga();
     newWin.setVisible( true);
     this.dispose();
    }//GEN-LAST:event_txtDatawargaActionPerformed

    private void txtKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeuanganActionPerformed
     JKeuangan newWin2 = new JKeuangan();
      newWin2.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_txtKeuanganActionPerformed

    private void btnTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanActionPerformed
//Tombol Simpan
       try {
            // Validasi input
            String nama = txtNama.getText().trim();
            String nik = txtNik.getText().trim();
            
            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nama warga tidak boleh kosong!");
                return;
            }
            
            if (nik.isEmpty()) {
                JOptionPane.showMessageDialog(null, "NIK tidak boleh kosong!");
                return;
            }
            
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sikopet", "root", "");
            
            String Jumlah = cmbJumlah.getSelectedItem().toString();
            
        String txtKategori = "";
        if (rb_Pemasukan.isSelected()){
            txtKategori = "Pemasukan";
        } else if (rb_Pengeluaran.isSelected()) {
            txtKategori = "Pengeluaran" ;
        } else {
            JOptionPane.showMessageDialog(null, "Pilih kategori terlebih dahulu!");
            return;
        }

        String tanggal = cmbTgl.getSelectedItem().toString() + "/" + cmbBln.getSelectedItem().toString() + "/" + cmbThn.getSelectedItem().toString();
        String nohp = txtNohp.getText().trim();
        
        // Escape single quotes untuk mencegah SQL injection
        nama = nama.replace("'", "\\'");
        nik = nik.replace("'", "\\'");
        nohp = nohp.replace("'", "\\'");
        
        cn.createStatement().executeUpdate("INSERT INTO data_warga (Nama_Warga, NIK, No_HP, Jumlah, Kategori, Tanggal) " +
"VALUES ('" + nama + "', '" + nik + "', '" + nohp + "', '" + Jumlah + "', '" + txtKategori + "', '" + tanggal + "')"
        );
        
        // Data berhasil disimpan ke data_warga
        // JKeuangan dan JLaporan akan membaca langsung dari tabel ini
        
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        
        // Clear form
        txtNama.setText("");
        txtNik.setText("");
        txtNohp.setText("");
        cmbJumlah.setSelectedIndex(0);
        cmbTgl.setSelectedIndex(0);
        cmbBln.setSelectedIndex(0);
        cmbThn.setSelectedIndex(0);
        
        bg_Kategori.clearSelection();
        
        getData();
        
     } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, "Gagal Simpan: " + ex.getMessage());
         ex.printStackTrace(); // Untuk debugging
     } catch (Exception ex) {
         JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
         ex.printStackTrace(); // Untuk debugging
     }
    }//GEN-LAST:event_btnTambahkanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    try {
    int selectedRow = tblDatawarga.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris yang akan dihapus!");
        return;
    }
    
    String nik = txtNik.getText();
    
    int confirm = JOptionPane.showConfirmDialog(null, 
            "Apakah yakin ingin menghapus data dengan NIK: " + nik + "?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
       Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sikopet", "root","");
       cn.createStatement().executeUpdate("DELETE FROM data_warga WHERE NIK='" + nik + "'");
       cn.createStatement().executeUpdate("ALTER TABLE data_warga AUTO_INCREMENT = 1");
       
       JOptionPane.showMessageDialog(null, "Data bBerhasil Dihapus");
       getData();
    }
    
}catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void menusaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusaveActionPerformed
    
    }//GEN-LAST:event_menusaveActionPerformed

    private void menuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitActionPerformed
       this.dispose();
    }//GEN-LAST:event_menuexitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
   try {
    int selectedRow = tblDatawarga.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Pilih baris yang akan diedit!");
        return;
    }

    String nikLama = tblDatawarga.getValueAt(selectedRow, 2).toString(); // kolom NIK (indeks ke-2)
    String nama = txtNama.getText().trim();
    String nikBaru = txtNik.getText().trim();
    String Nohp = txtNohp.getText().trim();
    String Jumlah = cmbJumlah.getSelectedItem().toString();
    String tgl = cmbTgl.getSelectedItem().toString();
    String Bln = cmbBln.getSelectedItem().toString();
    String Thn = cmbThn.getSelectedItem().toString();
    
    // Validasi input
    if (nama.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama warga tidak boleh kosong!");
        return;
    }
    
    if (nikBaru.isEmpty()) {
        JOptionPane.showMessageDialog(null, "NIK tidak boleh kosong!");
        return;
    }
    
    String Kategori = "";
    if (rb_Pemasukan.isSelected()) {
        Kategori = "Pemasukan";
    } else if (rb_Pengeluaran.isSelected()) {
        Kategori = "Pengeluaran";
    } else {
        JOptionPane.showMessageDialog(null, "Pilih kategori terlebih dahulu!");
        return;
    }
    
    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sikopet", "root", "");
    String tanggalUpdate = tgl + "/" + Bln + "/" + Thn;
    
    // Menggunakan PreparedStatement untuk keamanan yang lebih baik
    String sql = "UPDATE data_warga SET Nama_Warga=?, NIK=?, No_HP=?, Jumlah=?, Kategori=?, Tanggal=? WHERE NIK=?";
    java.sql.PreparedStatement pstmt = cn.prepareStatement(sql);
    
    pstmt.setString(1, nama);
    pstmt.setString(2, nikBaru);
    pstmt.setString(3, Nohp);
    pstmt.setString(4, Jumlah);
    pstmt.setString(5, Kategori);
    pstmt.setString(6, tanggalUpdate);
    pstmt.setString(7, nikLama);
    
    int rowsUpdated = pstmt.executeUpdate();
    
    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        
        // Clear form setelah update berhasil
        txtNama.setText("");
        txtNik.setText("");
        txtNohp.setText("");
        cmbJumlah.setSelectedIndex(0);
        cmbTgl.setSelectedIndex(0);
        cmbBln.setSelectedIndex(0);
        cmbThn.setSelectedIndex(0);
        bg_Kategori.clearSelection();
        
        getData();
    } else {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan atau tidak ada perubahan!");
    }
    
    pstmt.close();
    cn.close();
    
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error SQL: " + ex.getMessage());
    ex.printStackTrace();
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    ex.printStackTrace();
}
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataWarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel Nohp;
    private javax.swing.ButtonGroup bg_Kategori;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambahkan;
    private javax.swing.JComboBox<String> cmbBln;
    private javax.swing.JComboBox<String> cmbJumlah;
    private javax.swing.JComboBox<String> cmbTgl;
    private javax.swing.JComboBox<String> cmbThn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menuexit;
    private javax.swing.JMenuItem menuopen;
    private javax.swing.JMenuItem menusave;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nik;
    private javax.swing.JRadioButton rb_Pemasukan;
    private javax.swing.JRadioButton rb_Pengeluaran;
    private javax.swing.JTable tblDatawarga;
    private javax.swing.JLabel tgl;
    private javax.swing.JMenuItem txtDatawarga;
    private javax.swing.JLabel txtKategori;
    private javax.swing.JMenuItem txtKeuangan;
    private javax.swing.JMenuItem txtLaporan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNohp;
    // End of variables declaration//GEN-END:variables

   private void getData() {
        int row = tblDatawarga.getRowCount();
        for (int a=0; a<row; a++){
            model.removeRow(0);
        }
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/sikopet","root","");
            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM data_warga");
            while(rs.next()){
                String data[] = {rs.getString(1),
                 rs.getString(2),
                 rs.getString(3),
                 rs.getString(4),
                 rs.getString(5),
                 rs.getString(6),
                 rs.getString(7)};
                model.addRow(data);
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
        }
      }}
