/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sikopet;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class JKeuangan extends javax.swing.JFrame {

    Connection cn;
    DefaultTableModel modelPemasukan, modelPengeluaran;

    public JKeuangan() {
        initComponents();
        
        connectDatabase();
        setupTableModels();
        loadData();
        
        // Posisi tengah layar
        setLocationRelativeTo(null);
    }

    // 🔗 Koneksi ke database
    void connectDatabase() {
        try {
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sikopet", "root", "");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal: " + e.getMessage());
        }
    }

    // 🧱 Inisialisasi model tabel
    void setupTableModels() {
        modelPemasukan = new DefaultTableModel(new String[]{"Nama", "NIK", "No HP", "Tanggal", "Jumlah"}, 0);
        modelPengeluaran = new DefaultTableModel(new String[]{"Nama", "NIK", "No HP", "Tanggal", "Jumlah"}, 0);

        tblpemasukan.setModel(modelPemasukan);
        tblpengeluaran.setModel(modelPengeluaran);
    }

    // 📥 Load data dari database ke tabel
    void loadData() {
        try {
            modelPemasukan.setRowCount(0);
            modelPengeluaran.setRowCount(0);
            Statement st = cn.createStatement();
            
            // Load data pemasukan dari data_warga
            ResultSet rsPemasukan = st.executeQuery("SELECT Nama_Warga, NIK, No_HP, Tanggal, Jumlah FROM data_warga WHERE Kategori = 'Pemasukan' OR Kategori = 'pemasukan'");
            while (rsPemasukan.next()) {
                // Konversi jumlah ke angka
                String jumlahStr = rsPemasukan.getString("Jumlah");
                String cleanJumlah = jumlahStr.replace("RP. ", "").replace("RP ", "").replace("RP.", "").replace(".", "").replace(",", "");
                int jumlahInt = 0;
                try {
                    jumlahInt = Integer.parseInt(cleanJumlah);
                } catch (NumberFormatException e) {
                    jumlahInt = 0;
                }
                
                Object[] row = {
                    rsPemasukan.getString("Nama_Warga"),
                    rsPemasukan.getString("NIK"),
                    rsPemasukan.getString("No_HP"),
                    rsPemasukan.getString("Tanggal"),
                    jumlahInt
                };
                modelPemasukan.addRow(row);
            }
            rsPemasukan.close();
            
            // Load data pengeluaran dari data_warga
            ResultSet rsPengeluaran = st.executeQuery("SELECT Nama_Warga, NIK, No_HP, Tanggal, Jumlah FROM data_warga WHERE Kategori = 'Pengeluaran' OR Kategori = 'pengeluaran'");
            while (rsPengeluaran.next()) {
                // Konversi jumlah ke angka
                String jumlahStr = rsPengeluaran.getString("Jumlah");
                String cleanJumlah = jumlahStr.replace("RP. ", "").replace("RP ", "").replace("RP.", "").replace(".", "").replace(",", "");
                int jumlahInt = 0;
                try {
                    jumlahInt = Integer.parseInt(cleanJumlah);
                } catch (NumberFormatException e) {
                    jumlahInt = 0;
                }
                
                Object[] row = {
                    rsPengeluaran.getString("Nama_Warga"),
                    rsPengeluaran.getString("NIK"),
                    rsPengeluaran.getString("No_HP"),
                    rsPengeluaran.getString("Tanggal"),
                    jumlahInt
                };
                modelPengeluaran.addRow(row);
            }
            rsPengeluaran.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpemasukan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpengeluaran = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuopen = new javax.swing.JMenuItem();
        menusave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        txtDatawarga = new javax.swing.JMenuItem();
        txtKeuangan = new javax.swing.JMenuItem();
        txtLaporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data : Pencatatan Keuangan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("PEMASUKAN");

        tblpemasukan.setBackground(new java.awt.Color(153, 153, 255));
        tblpemasukan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblpemasukan.setForeground(new java.awt.Color(255, 255, 255));
        tblpemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblpemasukan);

        tblpengeluaran.setBackground(new java.awt.Color(153, 153, 255));
        tblpengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblpengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        tblpengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblpengeluaran);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("PENGELUARAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        menuopen.setText("Open");
        menuopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuopenActionPerformed(evt);
            }
        });
        jMenu1.add(menuopen);

        menusave.setText("Save");
        menusave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusaveActionPerformed(evt);
            }
        });
        jMenu1.add(menusave);
        jMenu1.add(jSeparator1);

        menuexit.setText("Exit");
        menuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitActionPerformed(evt);
            }
        });
        jMenu1.add(menuexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Input Data");

        txtDatawarga.setText("Data Warga");
        txtDatawarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatawargaActionPerformed(evt);
            }
        });
        jMenu2.add(txtDatawarga);

        txtKeuangan.setText("Pencatatan Keuangan");
        txtKeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeuanganActionPerformed(evt);
            }
        });
        jMenu2.add(txtKeuangan);

        txtLaporan.setText("Laporan");
        txtLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLaporanActionPerformed(evt);
            }
        });
        jMenu2.add(txtLaporan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLaporanActionPerformed
      JLaporan newWin2 = new JLaporan();
      newWin2.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_txtLaporanActionPerformed

    private void menusaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menusaveActionPerformed

    private void txtDatawargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatawargaActionPerformed
      DataWarga newWin = new DataWarga();
     newWin.setVisible( true);
     this.dispose();
    }//GEN-LAST:event_txtDatawargaActionPerformed

    private void menuopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuopenActionPerformed
      
    }//GEN-LAST:event_menuopenActionPerformed

    private void txtKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeuanganActionPerformed
      JKeuangan newWin2 = new JKeuangan();
      newWin2.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_txtKeuanganActionPerformed

    private void menuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitActionPerformed
       this.dispose();
    }//GEN-LAST:event_menuexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JKeuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuexit;
    private javax.swing.JMenuItem menuopen;
    private javax.swing.JMenuItem menusave;
    private javax.swing.JTable tblpemasukan;
    private javax.swing.JTable tblpengeluaran;
    private javax.swing.JMenuItem txtDatawarga;
    private javax.swing.JMenuItem txtKeuangan;
    private javax.swing.JMenuItem txtLaporan;
    // End of variables declaration//GEN-END:variables

    // Method untuk refresh data
    public void refreshData() {
        loadData();
    }
}
